---

# see https://stackoverflow.com/questions/67273590/pip-21-1-cant-import-invalidschemecombination
- name: fix broken pip package
  block:
    - name: detect pip init
      find:
        paths: "/usr/lib/python{{ ansible_python.version.major }}.{{ ansible_python.version.minor }}/site-packages/pip/"
        file_type: file
        patterns:
          - "__init__.py"
        recurse: false
      register: found_init

    - name: define init file
      set_fact:
        __pip_init: "{{ found_init.files | sort(attribute='path', reverse=True) | map(attribute='path') | list | first }}"
      when:
        - found_init.files is defined
        - found_init.files | count > 0

    - name: get version string from init file
      shell:
        grep __version__ {{ __pip_init }} | cut -d '"' -f2
      register: __pip_version
      when:
        - __pip_init is defined

    - name: remove incompatible version
      block:
        #
        - name: remove incompatible python-pip package (version {{ __pip_version.stdout }})
          package:
            name: python-pip
            state: absent
        - name: use python module ensurepip
          become: true
          shell:
            rm -rf /usr/lib/python{{ ansible_python.version.major }}.{{ ansible_python.version.minor }}/site-packages/pip* ;
            python -m ensurepip --default-pip --upgrade
          args:
            warn: false

        - name: update pip3 to latest
          pip:
            name: pip
            state: latest
            executable: pip3
            umask: "0022"
      when:
        - __pip_version.stdout is version('21.0', '<=')
  when:
    - ansible_os_family | lower == 'archlinux'

...
