---
name: many property files

on:
  schedule:
    - cron: "10 4 * * 0"
  workflow_dispatch:
  workflow_run:
    workflows:
      - "code linter"
    branches:
      - main
      - feature/**
      - fix/**
    types:
      - completed

defaults:
  run:
    working-directory: 'ansible-container'

jobs:
  deb:
    name: "${{ matrix.image }} / ansible: ${{ matrix.ansible-version }}"
    runs-on: ubuntu-20.04
    if: ${{ github.event_name == 'schedule' || github.event.workflow_run.conclusion == 'success' }}
    strategy:
      fail-fast: false
      matrix:
        image:
          - debian:11
        ansible-version:
          - '6.1'
          - '7.0'
        python:
          # '3.x'
          - '3.10'
          - '3.11'
        scenario:
          - many-properties

    steps:
      - name: check out the codebase.
        uses: actions/checkout@v3
        with:
          path: 'ansible-container'

      - name: 🐍 set up python
        uses: actions/setup-python@v4
        with:
          python-version: "${{ matrix.python }}"

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r test-requirements.txt

      - name: docker info
        run: |
          docker info

      - name: filesystems
        run: |
          cat /proc/filesystems

      - name: docker daemon config
        run: |
          cat /etc/docker/daemon.json
          sudo service docker stop
          sudo rm -rf /var/lib/docker/aufs
          sudo rm -f /var/lib/docker/linkgraph.db
          sudo service docker start

      - name: test with tox
        run: |
          make \
            test \
            -e TOX_SCENARIO="${{ matrix.scenario }}" \
            -e TOX_ANSIBLE="ansible_${{ matrix.ansible-version }}" \
            -e DISTRIBUTION="${{ matrix.image }}"

        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          DISTRIBUTION: ${{ matrix.image }}
